[package]
name = "ssddOnTop"
version = "0.1.0"
edition = "2021"

[dependencies]
macros = {path = "./macros"}
macros_common = {path = "./macros-common"}
tokio = {version = "1.40.0", features = ["full"]}
tracing = "0.1.40"
hyper = {version = "1.4.1",features = ["http1","server"]}
hyper-util = {version = "0.1.8", features = ["tokio"]}
http-body-util = "0.1.2"
bytes = "1.7.1"
anyhow = "1.0.87"
async-graphql = {version = "7.0.9", features = ["dynamic-schema"]}
serde_json = "1.0.127"
serde = { version = "1.0.210", features = ["derive"] }
async-graphql-value = "7.0.9"
serde_path_to_error = "0.1.16"
num_cpus = "1.16.0"
reqwest = "0.11"
nom = "7.1.3"
serde_json_borrow = "0.6.0"
derive-getters = "0.5.0"
indexmap = "2.5.0"
derive_more = "0.99.18"
indenter = "0.3.3"
derive_setters = "0.1.6"
fxhash = "0.2.1"
strum_macros = "0.26.4"
http-cache-reqwest = { version = "0.13.0", features = [
    "manager-moka",
], default-features = false }
reqwest-middleware = "0.2.5"
http-cache-semantics = { version = "1.0.1", default-features = false, features = ["with_serde", "reqwest"]}
moka = { version = "0.12.7", default-features = false, features = [
    "future",
]}
async-trait = "0.1.82"
ttl_cache = "0.5.1"
futures-util = "0.3.30"
http = "1.1.0"
url = "2.5.2"
schemars = {version = "0.8.17", features = ["derive"]}

[dev-dependencies]
http-cache = "0.18.0"

[workspace]
members = []
